name: PHP Composer

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"

    name: PHP ${{ matrix.php-versions }} test
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests
      run: composer test
